apiVersion: v1
kind: Service
metadata:
  name: {{ include "ptt.gateway.fullname" . }}
  labels:
    {{- include "ptt.gateway.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8888
      name: http
      nodePort: 30036
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "ptt.gateway.selectorLabels" . | nindent 4 }}
