apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ptt.writeside.fullname" . }}
  labels:
    {{- include "ptt.writeside.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.writeside.replicaCount }}
  selector:
    matchLabels:
      {{- include "ptt.writeside.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ptt.writeside.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ template "ptt.name" . }}-{{ .Values.writeside.name }}
          image: "{{ .Values.writeside.image.repository }}:{{ .Values.writeside.image.tag | default .Values.pttVersion }}"
          imagePullPolicy: {{ .Values.writeside.image.pullPolicy }}
          env:
            - name: WRITESIDE_JDBC_URL
              value: "jdbc:postgresql://postgresql/ptt"
            - name: WRITESIDE_LISTEN_HOST
              value: "0.0.0.0"
            - name: API_URL
              value: "http://localhost:30036"
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
