apiVersion: v1
kind: Service
metadata:
  name: {{ include "ptt.writeside.fullname" . }}
  labels:
    {{- include "ptt.writeside.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8082
      name: http
      targetPort: 8082
      protocol: TCP
  selector:
    {{- include "ptt.writeside.selectorLabels" . | nindent 4 }}
